// template/rspack-react-template/src/HoistNodePath.jsx
import { useEffect, useRef } from 'react';

export default function ({ topSelector, nodePath }) {
    const ref = useRef(null);
    useEffect(() => {
        let el = ref.current.parentNode;
        do {
            if(el.matches(topSelector)) {
                break;
            }
            el = el.parentNode;
        } while(el);
        el.setAttribute('nodepath', nodePath);
    })
    return (
        <div ref={ref}></div>
    )
}

// template/rspack-vue-template/src/HoistNodePath.vue
<template>
    <div></div>
</template>
<script>
export default {
    props: {
        nodePath: String,
        topSelector: String,
    },
    mounted() {
        let el = this.$el.parentNode;
        do {
            if(el.matches(this.topSelector)) {
                break;
            }
            el = el.parentNode;
        } while(el);
        el.setAttribute('nodepath', this.nodePath);
    }
}
</script>
